# Generated by Django 2.2.4 on 2019-11-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uname', models.CharField(max_length=30)),
                ('uemail', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(default=False, max_length=20)),
            ],
        ),
    ]
