# Generated by Django 2.2.4 on 2019-11-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_donor_last_donate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='last_donate_date',
            field=models.DateField(),
        ),
    ]
