# Generated by Django 2.2.4 on 2019-11-03 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20191103_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='last_donate_date',
        ),
    ]
