# Generated by Django 2.2.4 on 2019-11-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20191104_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='upass',
            field=models.CharField(max_length=10),
        ),
    ]
