# Generated by Django 2.2.4 on 2019-11-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20191104_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='uname',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='admin',
            name='upass',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
