# Generated by Django 2.2.4 on 2019-11-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_auto_20191104_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='upass',
        ),
        migrations.AddField(
            model_name='admin',
            name='up',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='admin',
            name='uname',
            field=models.CharField(max_length=20),
        ),
    ]
